### ISSUE TITLE
Cannot start snap 3.0.0 with i3wm

### ISSUE THREAD

**Issue by made4this** [oitsjustjose/Overleaf-Desktop#7]
Thanks for the snap update. Unfortunately, it doesn't start for me on Regolith Linux 20.04 (Ubuntu).
If I call "overleaf" from command line, it returns immediately and no window occurs.
I even restarted my whole system - no window at all.

Awkward - that's just what should **not** happen to a snap _by design_, right?

PS: Just want to add the fact, that tiling window managers (like i3wm in my case) tend to remove the title bar.

**Comment by DrRosental** [comment]
I reinstalled it and now it works. However, maybe look at it to help the updating people. Thanks for your work!

**Comment by oitsjustjose** [comment]
Agreed, that's odd behavior. I'll look into i3wm title bar issues. Maybe I'll start including my own titlebar like I do in Gmail Desktop.

**Comment by DrRosental** [comment]
Sorry, have to reopen it: After reinstall I am able to start it a single time and then the behavior is as before.

**Comment by DrRosental** [comment]
So `gdb overleaf` got me
`need to run as root or suid`
so it seems to be some awkward need for more permissions after the first (successful!) run.
I tried to install with "--classic" but it gets "ignored for strictly confined snap overleaf".

**Comment by DrRosental** [comment]
I'm done with it. Turns out there's basically no reason for twm people to use Overleaf-Desktop due to [the fact that you have a browser](https://superuser.com/questions/459775/how-can-i-launch-a-browser-with-no-window-frame-or-tabs-address-bar). Example using chromium:

`chromium-browser --app=https://overleaf.com`

**Comment by elmeunick9** [comment]
I'd thought the idea was to have an offline editor that works on your own machine, thus overcoming overleaf limits of compile time and file size, plus having git and Dropbox/Drive/... integration out of the box for free (since the files are in your computer). This can already by done by self-hosting with docker, but this looked like a much easier solution. Guess I was wrong.
