### ISSUE TITLE
Shows only a white screen

### ISSUE THREAD

**Issue by probonopd** [oitsjustjose/Overleaf-Desktop#8]
Shows only a white screen when not connected to the internet?

![image](https://user-images.githubusercontent.com/2480569/88906084-89395100-d246-11ea-8670-47d5bc5bf297.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/1552#issuecomment-666255430

**Comment by oitsjustjose** [comment]
Well... yeah? Since I don’t work for overleaf I’m not allowed to directly use their source code and their servers. Even if I did, if you’re offline you can’t use overleaf so why should you be able to use overleaf desktop? If you want an offline LaTEX editor I suggest installing it locally and using one of the many local tools like R-Studio

**Comment by probonopd** [comment]
Ah, I see. I always think it is good practice to have a window come up "you need to connect to the internet" or something like it rather than just assuming that everyone is online all the time.
